#!/usr/bin/perl

use strict;
use warnings;

use YAML::PP;
use FindBin;
use Getopt::Long;

BEGIN { push @::INC, '/usr/lib/build', "$FindBin::Bin/../lib"; }

use Build::Rpm;
use Kanku::ReleaseTools::Changelog;

our $dry_run;
my $dst_branch = "master";

if (!
  GetOptions(
    'branch=s'=>\$dst_branch, 
    'dry-run'=>\$dry_run
  )
) {
  die "Error in command line arguments\n";
}

my $changelog = Kanku::ReleaseTools::Changelog->new(
  destination_branch => $dst_branch,
  outdir             => "$FindBin::Bin/..",
  blog_dir           => "$FindBin::Bin/../blog",
);

my $log    = $changelog->create_new_changelog_entries();

if (!$log) {
  print "No new changelog entries found. Exiting...\n";
  if ($dry_run) {
    print "#### CURRENT CHANGELOG CONTENT####\n".
      $changelog->current_changelog_content;
  }
  exit 0;
}

$log .= $changelog->current_changelog_content;

if (!$dry_run) {
  my $file     = $changelog->write_new_changelog($log);
  my @new_revs = $changelog->new_releases;
  my $message  = "[doc] updated $file. New revisions: (@new_revs)";
  $changelog->stash_and_commit($file, $message);
} else {
  print $log;
}

exit 0;
