#!/usr/bin/perl

use strict;

use YAML::PP;
use Data::Dumper;
use FindBin;

BEGIN { push @::INC, "$FindBin::Bin/../lib"; };

use Kanku::ReleaseTools::ReleaseNotes;

my $release = $ARGV[0];
die "Please specify a release version as first parameter\n" unless $release;

my $notes = Kanku::ReleaseTools::ReleaseNotes->new(
  destination_branch => "master",
  outdir             => "$FindBin::Bin/..",
  blog_dir           => "$FindBin::Bin/../blog",
  release            => $release,
);

my $rnotes = $notes->blog_releases;
my $yaml = YAML::PP::LoadFile($rnotes->{$release});
$notes->create($yaml);
$notes->stash_and_commit();

exit 0;
